package com.micasong.player

import com.micasong.player.data.model.OfflineState
import com.micasong.player.data.model.Track

/** Convenience builder for constructing [Track] fixtures in unit tests. */
fun track(
    id: Long,
    title: String = "Track $id",
    artist: String = "Artist",
    artistId: Long = id,
    album: String = "Album",
    albumId: Long = id,
    year: Int? = null,
    genre: String? = null,
    durationMs: Long = 200_000,
    rating: Int = 0,
    playCount: Int = 0,
    favorite: Boolean = false,
    lastPlayed: Long = 0,
    excludedFromMixes: Boolean = false,
    artworkUri: String? = "art://$id",
    offlineState: OfflineState = OfflineState.NONE,
    isAudiobook: Boolean = false,
): Track = Track(
    id = id,
    providerId = 1,
    mediaUri = "uri://$id",
    title = title,
    albumId = albumId,
    albumName = album,
    artistId = artistId,
    artistName = artist,
    albumArtist = artist,
    trackNumber = id.toInt(),
    discNumber = 1,
    durationMs = durationMs,
    year = year,
    genre = genre,
    mimeType = "audio/flac",
    bitrate = null,
    sampleRate = null,
    bitDepth = null,
    sizeBytes = null,
    artworkUri = artworkUri,
    isFavorite = favorite,
    userRating = rating,
    playCount = playCount,
    skipCount = 0,
    lastPlayed = lastPlayed,
    resumePositionMs = 0,
    isAudiobook = isAudiobook,
    excludedFromMixes = excludedFromMixes,
    offlineState = offlineState,
)
